# Generated by Django 5.2.1 on 2025-06-12 13:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('nutrition_type', models.CharField(choices=[('Protein', 'Protein'), ('Carbohydrate', 'Carbohydrate'), ('Fat', 'Fat'), ('Fiber', 'Fiber'), ('Vitamin', 'Vitamin'), ('Mineral', 'Mineral'), ('Mixed', 'Mixed')], max_length=20)),
                ('calories_per_serving', models.FloatField(help_text='Calories per serving')),
                ('protein', models.FloatField(default=0.0, help_text='Protein (g)')),
                ('carbs', models.FloatField(default=0.0, help_text='Carbohydrates (g)')),
                ('fats', models.FloatField(default=0.0, help_text='Fats (g)')),
                ('goal_type', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='nutrition_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='workout_images/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Weight Loss', ' Loss'), ('Weight Gain', 'Weight Gain')], max_length=20)),
                ('met_value', models.FloatField(default=4.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('height', models.FloatField(help_text='Enter height in centimeters')),
                ('weight', models.FloatField(help_text='Enter weight in kilograms')),
                ('fitness_level', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain')], max_length=100)),
                ('workout_name', models.CharField(max_length=100)),
                ('workout_duration', models.IntegerField()),
                ('workout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=100)),
                ('servings', models.FloatField(default=1.0, help_text='Number of servings')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal_type', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('General Fitness', 'General Fitness')], default='General Fitness', max_length=50)),
                ('total_calories', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitApp.userprofile')),
            ],
        ),
    ]
