# Generated by Django 5.2 on 2025-04-15 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=100)),
                ('servings', models.FloatField(default=1.0, help_text='Number of servings')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal_type', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('General Fitness', 'General Fitness')], default='General Fitness', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitApp.userprofile')),
            ],
        ),
    ]
