# Generated by Django 5.2 on 2025-04-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitApp', '0002_add_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_nutrition',
            name='total_calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='admin_nutrition',
            name='goal_type',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain')], max_length=50),
        ),
    ]
